version: '3.9'

services:
  necesse-server:
    image: ghcr.io/driftywinds/necesse-server:latest
    container_name: necesse-server
    stdin_open: true
    tty: true
    ports:
      - "14159:14159/tcp"
      - "14159:14159/udp"
    volumes:
      - ./data:/root/.config/Necesse
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx2G -Xms1G
      - SERVER_OPTS="-nogui -world <YOUR WORLD NAME HERE> -slots 20 -owner <YOUR CHARACTER NAME HERE> -pausewhenempty 1 -password <YOUR PASSWORD HERE>"

    # Uncomment below to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
    #     reservations:
    #       cpus: '1'
    #       memory: 2G
